autoInstallPeers: false
strictPeerDependencies: false

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@jderstd/hono"
    - "@jderstd/hono-openapi"
    - "ts-vista"
    - "vitend"
